### PR TITLE
Remove Unused Dependency: Requests

### PR DESCRIPTION
**Pull request by gdrosos**
## Summary

This pull request removes the unused dependency `requests` from the `pyproject.toml` & poetry configuration files. This detection and removal is a finding from ongoing research aimed at identifying and eliminating code bloat within software projects.

## Rationale

Upon the analysis of the source code, we detected that the `requests` is no longer utilised in the source code while it still remains as a requirement in the project's dependencies files. Since it is no longer being directly utilized, removing this unused dependency will reduce the overall footprint of the application, mitigate potential security risks, and simplify the dependency management process.

## Changes

- Removed the `requests` dependency from the `pyproject.toml` file.
- Removed the `requests` dependency from the Poetry configuration file.
- 
## Impact

- **Reduced Package Size**: The removal of this unused dependency will lead to a decrease in the overall size of the installed packages.
- **Simplified Dependency Tree**: Fewer dependencies make the project easier to maintain and can speed up installation.

### CODE REVIEW

**Comment by gdrosos** [comment]
Some additional context: `requests` was added on 138502e40edacf9d214a6529e25b6b9c979d9a53. At this state of the repo the dependency was used in various parts of the project, but it was gradually removed (e.g. c00c26ada54d894886df011a36dcfee76812b2b6) and now it appears to be unused.

**Comment by willronchetti** [comment]
Please bump a patch version in `pyproject.toml` and add a `CHANGELOG` entry and I will allow a build and we will take this. Thanks for doing it!

**Comment by gdrosos** [comment]
You are welcome, @willronchetti.
I've bumped the version to 3.3.3 in `pyproject.toml` and added the respective `CHANGELOG` entry. Please let me know if there are any other changes needed.
Thank you for your feedback!

**Comment by gdrosos** [comment]
I also reverted the changes in `poetry.lock` since I wasn't quite sure if I should be the one autogenerating it after the updates in `pyproject.toml`

**Comment by gdrosos** [comment]
Hello @willronchetti , I commited the updated version of `poetry.lock`

**Comment by willronchetti** [comment]
This passed our tests locally so I am merging, thanks for the contribution!

**Pull request merged**
